"""Preview tool — generates HTML specimen page, opens in browser."""

from __future__ import annotations

import os
import sys
import tempfile
import webbrowser
from dataclasses import fields
from typing import TYPE_CHECKING

from .svg_export import glyph_to_svg
from . import settings

if TYPE_CHECKING:
    from .alphabet import Alphabet


def _style_table_html(alphabet: Alphabet) -> str:
    """Generate an HTML table of style parameters."""
    rows: list[str] = []
    for f in fields(alphabet.style):
        val = getattr(alphabet.style, f.name)
        if hasattr(val, "value"):
            val = val.value  # Enum
        rows.append(f"<tr><td>{f.name}</td><td>{val}</td></tr>")
    return "\n".join(rows)


def generate_html(alphabet: Alphabet, glyph_size: int | None = None) -> str:
    """Generate a self-contained HTML specimen page."""
    if glyph_size is None:
        try:
            glyph_size = int(settings.get_export()["preview_glyph_size"])
        except (KeyError, FileNotFoundError):
            glyph_size = 120
    glyph_svgs: list[str] = []
    for glyph in alphabet:
        svg = glyph_to_svg(glyph, size=glyph_size, style=alphabet.style)
        glyph_svgs.append((glyph.label, svg))

    preset_info = f" | Preset: {alphabet.preset_name}" if alphabet.preset_name else ""

    glyph_cells = ""
    for label, svg in glyph_svgs:
        glyph_cells += f"""
        <div class="glyph-cell">
            <div class="glyph-svg">{svg}</div>
            <div class="glyph-label">{label}</div>
        </div>"""

    style_rows = _style_table_html(alphabet)

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>GlyphForge — Seed {alphabet.seed}{preset_info}</title>
<style>
    body {{
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace;
        max-width: 1000px;
        margin: 0 auto;
        padding: 20px;
        background: #fafafa;
        color: #333;
    }}
    h1 {{ font-size: 24px; margin-bottom: 5px; }}
    .meta {{ color: #888; font-size: 14px; margin-bottom: 20px; }}
    .glyph-grid {{
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax({glyph_size + 20}px, 1fr));
        gap: 12px;
        margin-bottom: 30px;
    }}
    .glyph-cell {{
        background: white;
        border: 1px solid #e0e0e0;
        border-radius: 6px;
        padding: 8px;
        text-align: center;
    }}
    .glyph-cell:hover {{
        border-color: #999;
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }}
    .glyph-svg svg {{
        width: {glyph_size}px;
        height: {glyph_size}px;
    }}
    .glyph-label {{
        font-size: 14px;
        color: #666;
        margin-top: 4px;
        font-weight: bold;
    }}
    details {{
        margin-top: 20px;
        border: 1px solid #e0e0e0;
        border-radius: 6px;
        background: white;
        padding: 12px;
    }}
    summary {{
        cursor: pointer;
        font-weight: bold;
        color: #555;
    }}
    table {{
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
        font-size: 13px;
    }}
    td {{
        padding: 3px 8px;
        border-bottom: 1px solid #f0f0f0;
    }}
    td:first-child {{
        font-weight: 500;
        color: #666;
        width: 220px;
    }}
</style>
</head>
<body>
<h1>GlyphForge Specimen</h1>
<div class="meta">Seed: {alphabet.seed}{preset_info}</div>

<div class="glyph-grid">
{glyph_cells}
</div>

<details>
<summary>Style Parameters</summary>
<table>
{style_rows}
</table>
</details>

<div class="meta" style="margin-top: 20px; font-size: 12px;">
    Generated by GlyphForge
</div>
</body>
</html>"""
    return html


def preview_alphabet(alphabet: Alphabet) -> str:
    """Generate HTML and open in browser. Returns the file path."""
    html = generate_html(alphabet)

    # Write to temp file
    fd, path = tempfile.mkstemp(suffix=".html", prefix="glyphforge_")
    with os.fdopen(fd, "w") as f:
        f.write(html)

    webbrowser.open(f"file://{os.path.abspath(path)}")
    return path


def save_preview(alphabet: Alphabet, path: str) -> str:
    """Save HTML preview to a specific path."""
    html = generate_html(alphabet)
    with open(path, "w") as f:
        f.write(html)
    return path


# -- Standalone usage: python -m glyphforge.preview [specimen.svg] --------

def main():
    """Standalone preview: generate a specimen from a random seed."""
    import glyphforge

    seed = 42
    if len(sys.argv) > 1:
        try:
            seed = int(sys.argv[1])
        except ValueError:
            print(f"Usage: python -m glyphforge.preview [seed]")
            sys.exit(1)

    alphabet = glyphforge.generate(seed=seed)
    path = preview_alphabet(alphabet)
    print(f"Preview saved to: {path}")


if __name__ == "__main__":
    main()
